### ISSUE TITLE
rtcagent crashes

### ISSUE THREAD

**Issue by ratetel** [sipcapture/rtcagent#10]
when we run it with rtcagent opensips -P9061 -S127.0.0.1 it crashes after a short period with 

opensips_2024/03/27 17:55:51 LETS SEND HEP
2024/03/27 17:55:51 %vwrite udp 127.0.0.1:52163->127.0.0.1:9061: write: connection refused

when we run it with rtcagent opensips -P9061 -S127.0.0.1 -d      it does not crash

**Comment by adubovikov** [comment]
ok, i will add reconnect. Do you have the panic log ?

**Comment by adubovikov** [comment]
closed as incomplete. Please send me a dump if it exitst
