### ISSUE TITLE
rtcagent writes all captured packet to syslog even after disabling debug

### ISSUE THREAD

**Issue by hamidrhashmi** [sipcapture/rtcagent#6]
I am running rtcagent service with the following command
```
/usr/bin/rtcagent kamailio -m /opt/kamailio/sbin/kamailio --hep-server="127.0.0.1" --hep-port="9060" --hep-transport="tcp" --debug=false
```

but rtcagent is still writing all captured packet to syslog

**Comment by hamidrhashmi** [comment]
I have retested with version `0.0.7` but rtcagent is still writing SIP messages to syslog.

**Comment by adubovikov** [comment]
it was fixed in the latest version
